name: Todo Check

on:
    pull_request:
      types: [opened]

jobs:
    todo-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run vibed-todo-action
              uses: Mikolaj-A-Kowalski/vibed-todo-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                todo-pattern: 'TODO'
                fix-pattern: 'Please fix me before merging'
